### PR TITLE
Fix GitHub test Actions

### PR DESCRIPTION
**Pull request by claudio-ferraro**

### CODE REVIEW

**Comment by royduin** [comment]
What was the problem and how is this going to fix it?

**Comment by claudio-ferraro** [comment]
The error was:

```Fatal error: Declaration of Orchestra Testbench TestCase::onNotSuccessfulTest(Throwable $exception): void must be compatible with PHPUnit Framework TestCase::onNotSuccessfulTest(Throwable $t): never in /app/vendor/orchestra/testbench-core/src/TestCase.php on line 141```

I have searched a few things about this on Google, but could not find an exact cause. Perhaps it has to do with an update.

I have now copied some of it from: https://github.com/laravel/framework/blob/10.x/.github/workflows/tests.yml and https://github.com/justbetter/laravel-magento-client/blob/main/.github/workflows/tests.yml. This uses `shivammathur/setup-php@v2` and `nick-fields/retry@v2`.

After applying this, I got the test working again.

**Comment by royduin** [comment]
There is just a mismatch between phpunit and orchestra, this feels like a detour around the problem with adding stuff which isn't used

**Comment by claudio-ferraro** [comment]
Okay I will look into it further. I'll close this PR for now.

**Pull request closed without merging**
